spring:
  application:
    name: springScheduledExample
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate: debug